name: Build and Release Simple Kafka App Java

on:
  push:
    tags:
      - 'simple-kafka-app-java-v*'

permissions:
  contents: read
  packages: write
  id-token: write # since we are usign buildx it needs write permission to be able to push to ghcr.io  

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Extract version from tag name
        run: echo "SHORT_TAG=${GITHUB_REF#refs/tags/simple-kafka-app-java-}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build and push multi-platform image
        working-directory: simple-kafka-app-java
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/elinesterov/simple-kafka-app-java:${{ env.SHORT_TAG }} \
            --build-arg VERSION=${{ env.SHORT_TAG }} \
            --push \
            .